"""Тексти головної сторінки (home v4) для cs / en / ru."""

HOME_COPY = {
    'cs': {
        'hero_eyebrow': 'Praha 1 · Prémiový masážní salon',
        'hero_title': 'Umění<br><em>relaxace</em><br>ve vašich rukou',
        'hero_sub': 'Certifikované masérky, privátní kabinety a luxusní atmosféra v srdci Prahy.',
        'hero_cta1': 'Rezervovat masáž',
        'hero_cta2': 'Naše masáže',
        'svc_label': 'Naše masáže',
        'svc_title': 'Relaxace pro každý moment',
        'svc_sub': 'Šest druhů masáže přizpůsobených vašemu tělu i mysli — od klasické švédské po aromaterapii.',
        'svc_btn': 'Zjistit více',
        'all_svc': 'Všechny masáže',
        'team_label': 'Náš tým',
        'team_title': 'Masérky',
        'team_sub': 'Certifikované specialistky s individuálním přístupem a hlubokými znalostmi masážních technik.',
        'all_team': 'Seznámit se s týmem',
        'proc_label': 'Vaše cesta k relaxaci',
        'proc_title': 'Každý detail<br>myslíme za vás',
        'faq_label': 'FAQ',
        'faq_title': 'Odpovědi na vaše otázky',
        'cta_label': 'Dopřejte si',
        'cta_title': 'Vaše tělo si<br>zaslouží péči',
        'cta_sub': 'Rezervujte si masáž online a nechte se unést luxusní atmosférou Black Diamond Spa.',
        'cta_btn1': 'Rezervovat nyní',
        'cta_btn2': 'Kontakt',
        'modal_close': 'Zavřít',
        'modal_svc_title': 'Nabízené masáže',
        'modal_reserve': 'Rezervovat termín',
        'steps': [
            ('Vyberte masáž', 'Prozkoumejte katalog a vyberte masáž, která nejlépe odpovídá vašim potřebám a přáním.'),
            ('Zvolte masérku', 'Každá z našich masérky má jedinečnou specializaci. Vyberte tu, jejíž styl vám vyhovuje.'),
            ('Potvrďte termín', 'Zvolte volný termín v online rozvrhu a potvrďte rezervaci. Potvrzení přijde e-mailem.'),
            ('Relaxujte', 'Přijďte 10 minut předem. Vše ostatní necháme na nás — váš čas je jen pro vás.'),
        ],
        'faqs': [
            ('Jak se připravit na masáž?', 'Doporučujeme přijít 10 minut předem, čistí a hydratovaní. Vyhněte se jídlu hodinu před masáží.'),
            ('Jak rezervovat masáž?', 'Online v sekci <a href="/cs/rozvrh/">Rozvrh</a> — vyberte masáž, masérku a volný termín. Potvrzení obdržíte e-mailem.'),
            ('Jak dlouho masáž trvá?', 'Závisí na zvoleném typu: od 60 minut (klasická, sportovní) do 90 minut (uvolňující masáž).'),
            ('Jak probíhá platba?', 'Přijímáme hotovost i platební karty. Platba probíhá na místě po skončení masáže.'),
            ('Nabízíte párovou masáž?', 'Ano, párová masáž je možná po domluvě. Kontaktujte nás pro rezervaci pro dvě osoby.'),
            ('Co je zahrnuto v ceně?', 'Masážní oleje, prostěradla a přístup do relaxační zóny jsou součástí každé masáže.'),
        ],
    },
    'en': {
        'hero_eyebrow': 'Prague 1 · Premium massage salon',
        'hero_title': 'The art<br>of <em>relaxation</em><br>in your hands',
        'hero_sub': 'Certified masseuses, private cabins and a luxurious atmosphere in the heart of Prague.',
        'hero_cta1': 'Book a massage',
        'hero_cta2': 'Our massages',
        'svc_label': 'Our massages',
        'svc_title': 'Relaxation for every moment',
        'svc_sub': 'Six types of massage tailored to your body and mind — from classic Swedish to aromatherapy.',
        'svc_btn': 'Learn more',
        'all_svc': 'All massages',
        'team_label': 'Our team',
        'team_title': 'Masseuses',
        'team_sub': 'Certified specialists with an individual approach and deep knowledge of massage techniques.',
        'all_team': 'Meet our team',
        'proc_label': 'Your path to relaxation',
        'proc_title': 'Every detail<br>thought through for you',
        'faq_label': 'FAQ',
        'faq_title': 'Answers to your questions',
        'cta_label': 'Treat yourself',
        'cta_title': 'Your body<br>deserves care',
        'cta_sub': 'Book your massage online and immerse yourself in the luxurious atmosphere of Black Diamond Spa.',
        'cta_btn1': 'Book now',
        'cta_btn2': 'Contact us',
        'modal_close': 'Close',
        'modal_svc_title': 'Offered massages',
        'modal_reserve': 'Book appointment',
        'steps': [
            ('Choose a massage', 'Browse our catalog and pick the massage that best fits your needs and wishes.'),
            ('Pick a masseuse', 'Each of our masseuses has a unique specialty. Choose the one whose style suits you.'),
            ('Confirm your slot', 'Select an available slot in the online schedule and confirm. Email confirmation follows.'),
            ('Relax', 'Arrive 10 minutes early. We take care of everything else — your time is yours alone.'),
        ],
        'faqs': [
            ('How to prepare for a massage?', 'Arrive 10 minutes early, clean and hydrated. Avoid eating one hour before your massage.'),
            ('How to book a massage?', 'Online in the <a href="/en/rozvrh/">Schedule</a> section — choose massage, masseuse and slot. Email confirmation follows.'),
            ('How long does a massage last?', 'Duration depends on type: from 60 minutes (classic, sports) to 90 minutes (relaxing).'),
            ('How does payment work?', 'We accept cash and cards. Payment is made on site after the massage.'),
            ('Do you offer couples massage?', 'Yes, couples massage is available upon request. Contact us to book for two.'),
            ('What is included in the price?', 'Massage oils, linens and access to the relaxation zone are included in every massage.'),
        ],
    },
    'ru': {
        'hero_eyebrow': 'Прага 1 · Премиальный массажный салон',
        'hero_title': 'Искусство<br><em>расслабления</em><br>в ваших руках',
        'hero_sub': 'Сертифицированные массажистки, приватные кабинеты и роскошная атмосфера в центре Праги.',
        'hero_cta1': 'Записаться на массаж',
        'hero_cta2': 'Наши массажи',
        'svc_label': 'Наши массажи',
        'svc_title': 'Расслабление для каждого момента',
        'svc_sub': 'Шесть видов массажа, подобранных для вашего тела и разума — от классического шведского до ароматерапии.',
        'svc_btn': 'Подробнее',
        'all_svc': 'Все массажи',
        'team_label': 'Наша команда',
        'team_title': 'Массажистки',
        'team_sub': 'Сертифицированные специалистки с индивидуальным подходом и глубокими знаниями массажных техник.',
        'all_team': 'Познакомиться с командой',
        'proc_label': 'Ваш путь к расслаблению',
        'proc_title': 'Каждая деталь<br>продумана за вас',
        'faq_label': 'FAQ',
        'faq_title': 'Ответы на ваши вопросы',
        'cta_label': 'Подарите себе',
        'cta_title': 'Ваше тело<br>заслуживает ухода',
        'cta_sub': 'Забронируйте массаж онлайн и погрузитесь в роскошную атмосферу Black Diamond Spa.',
        'cta_btn1': 'Забронировать',
        'cta_btn2': 'Контакты',
        'modal_close': 'Закрыть',
        'modal_svc_title': 'Предлагаемые массажи',
        'modal_reserve': 'Забронировать',
        'steps': [
            ('Выберите массаж', 'Изучите каталог и выберите массаж, который лучше всего отвечает вашим потребностям.'),
            ('Выберите массажистку', 'У каждой массажистки уникальная специализация. Выберите ту, чей стиль вам подходит.'),
            ('Подтвердите время', 'Выберите свободный слот в онлайн-расписании и подтвердите. Подтверждение придёт по email.'),
            ('Расслабьтесь', 'Приходите за 10 минут. Всё остальное — на нас. Ваше время только для вас.'),
        ],
        'faqs': [
            ('Как подготовиться к массажу?', 'Приходите за 10 минут, чистым и гидратированным. Избегайте еды за час до массажа.'),
            ('Как забронировать массаж?', 'Онлайн в разделе <a href="/ru/rozvrh/">Расписание</a> — выберите массаж, массажистку и время.'),
            ('Как долго длится массаж?', 'От 60 минут (классический, спортивный) до 90 минут (расслабляющий).'),
            ('Как происходит оплата?', 'Принимаем наличные и карты. Оплата на месте после массажа.'),
            ('Предлагаете парный массаж?', 'Да, парный массаж возможен по запросу. Свяжитесь с нами для бронирования.'),
            ('Что включено в цену?', 'Масляные составы, простыни и доступ к зоне отдыха включены в каждый массаж.'),
        ],
    },
}

FEATURED_SERVICE_SLUGS = ('klasicka-masaz', 'cbd-relaxacni-masaz', 'aromaterapie')


def get_home_copy(lang):
    code = (lang or 'cs')[:2]
    return HOME_COPY.get(code, HOME_COPY['cs'])
