"""Тексти головної сторінки (home v4) для cs / en / ru."""

HOME_COPY = {
    'cs': {
        'hero_title': 'Místo<br><em>odpočinku</em><br>a klidu',
        'hero_sub': 'Nechte stres za dveřmi. Privátní kabinety, vědomá masáž a atmosféra, kde si tělo i mysl konečně oddychnou.',
        'hero_cta1': 'Rezervovat masáž',
        'hero_cta2': 'Naše masáže',
        'svc_label': 'Naše masáže',
        'svc_title': 'Relaxace pro každý moment',
        'svc_sub': 'Masáže přizpůsobené vašemu tělu i mysli — VIP, relaxační, pro ženy i pro páry.',
        'svc_btn': 'Zjistit více',
        'all_svc': 'Všechny masáže',
        'team_label': 'Náš tým',
        'team_title': 'Masérky',
        'team_sub': 'Zkušené specialistky s individuálním přístupem a hlubokými znalostmi masážních technik.',
        'all_team': 'Seznámit se s týmem',
        'proc_label': 'Vaše cesta k relaxaci',
        'proc_title': 'Každý detail<br>myslíme za vás',
        'reviews_label': 'Recenze',
        'reviews_title': 'Co říkají naši hosté',
        'reviews_sub': 'Autentické hodnocení z Google Maps.',
        'reviews_empty': 'Recenze brzy doplníme z Google Maps.',
        'reviews_all': 'Všechny recenze na Google',
        'faq_label': 'FAQ',
        'faq_title': 'Odpovědi na vaše otázky',
        'faq_all': 'Všechny otázky',
        'cta_label': 'Dopřejte si',
        'cta_title': 'Vaše tělo si<br>zaslouží péči',
        'cta_sub': 'Rezervujte si masáž online a nechte se unést luxusní atmosférou Black Diamond Spa.',
        'cta_btn1': 'Rezervovat nyní',
        'cta_btn2': 'Kontakt',
        'modal_close': 'Zavřít',
        'modal_svc_title': 'Nabízené masáže',
        'modal_reserve': 'Rezervovat termín',
        'steps': [
            ('Vyberte masáž', 'Prozkoumejte katalog a vyberte masáž, která nejlépe odpovídá vašim potřebám a přáním.'),
            ('Napište nám', 'Rezervace vyřizujeme přes WhatsApp nebo telefonicky — napište nám a domluvíme termín, který vám vyhovuje.'),
            ('Potvrďte termín', 'Termín vám obratem potvrdíme zprávou. Žádná registrace, žádné čekání.'),
            ('Relaxujte', 'Přijďte 10 minut předem. Vše ostatní necháme na nás — váš čas je jen pro vás.'),
        ],
        'faqs': [
            ('Jak se připravit na masáž?', 'Doporučujeme přijít 10 minut předem, čistí a hydratovaní. Vyhněte se jídlu hodinu před masáží.'),
            ('Jak rezervovat masáž?', 'Napište nám na WhatsApp nebo zavolejte — domluvíme termín, který vám vyhovuje, a obratem ho potvrdíme.'),
            ('Jak dlouho masáž trvá?', 'Standardní masáž trvá 60 minut, prodloužené varianty 90 minut. Délku si vyberete při rezervaci.'),
            ('Jak probíhá platba?', 'Přijímáme hotovost i platební karty. Platba probíhá na místě po skončení masáže.'),
            ('Nabízíte párovou masáž?', 'Ano, párová masáž je možná po domluvě. Kontaktujte nás pro rezervaci pro dvě osoby.'),
            ('Co je zahrnuto v ceně?', 'Masážní oleje, prostěradla a přístup do relaxační zóny jsou součástí každé masáže.'),
        ],
    },
    'en': {
        'hero_title': 'A place for<br><em>rest</em><br>and calm',
        'hero_sub': 'Leave stress at the door. Private cabins, mindful massage and an atmosphere where body and mind truly recover.',
        'hero_cta1': 'Book a massage',
        'hero_cta2': 'Our massages',
        'svc_label': 'Our massages',
        'svc_title': 'Relaxation for every moment',
        'svc_sub': 'Massages tailored to your body and mind — VIP, relaxation, for women and for couples.',
        'svc_btn': 'Learn more',
        'all_svc': 'All massages',
        'team_label': 'Our team',
        'team_title': 'Masseuses',
        'team_sub': 'Experienced specialists with an individual approach and deep knowledge of massage techniques.',
        'all_team': 'Meet our team',
        'proc_label': 'Your path to relaxation',
        'proc_title': 'Every detail<br>thought through for you',
        'reviews_label': 'Reviews',
        'reviews_title': 'What our guests say',
        'reviews_sub': 'Authentic ratings from Google Maps.',
        'reviews_empty': 'Reviews will appear here from Google Maps.',
        'reviews_all': 'All reviews on Google',
        'faq_label': 'FAQ',
        'faq_title': 'Answers to your questions',
        'faq_all': 'All questions',
        'cta_label': 'Treat yourself',
        'cta_title': 'Your body<br>deserves care',
        'cta_sub': 'Book your massage online and immerse yourself in the luxurious atmosphere of Black Diamond Spa.',
        'cta_btn1': 'Book now',
        'cta_btn2': 'Contact us',
        'modal_close': 'Close',
        'modal_svc_title': 'Offered massages',
        'modal_reserve': 'Book appointment',
        'steps': [
            ('Choose a massage', 'Browse our catalog and pick the massage that best fits your needs and wishes.'),
            ('Message us', 'We take bookings via WhatsApp or phone — write to us and we will arrange a time that suits you.'),
            ('Confirm your slot', 'We confirm your appointment right away by message. No registration, no waiting.'),
            ('Relax', 'Arrive 10 minutes early. We take care of everything else — your time is yours alone.'),
        ],
        'faqs': [
            ('How to prepare for a massage?', 'Arrive 10 minutes early, clean and hydrated. Avoid eating one hour before your massage.'),
            ('How to book a massage?', 'Message us on WhatsApp or give us a call — we will arrange a time that suits you and confirm it right away.'),
            ('How long does a massage last?', 'A standard massage lasts 60 minutes, extended options 90 minutes. You choose the length when booking.'),
            ('How does payment work?', 'We accept cash and cards. Payment is made on site after the massage.'),
            ('Do you offer couples massage?', 'Yes, couples massage is available upon request. Contact us to book for two.'),
            ('What is included in the price?', 'Massage oils, linens and access to the relaxation zone are included in every massage.'),
        ],
    },
    'ru': {
        'hero_title': 'Место<br><em>отдыха</em><br>и покоя',
        'hero_sub': 'Оставьте стресс за дверью. Приватные кабинеты, сознательный массаж и атмосфера, где тело и разум наконец отдохнут.',
        'hero_cta1': 'Записаться на массаж',
        'hero_cta2': 'Наши массажи',
        'svc_label': 'Наши массажи',
        'svc_title': 'Расслабление для каждого момента',
        'svc_sub': 'Массажи, подобранные под ваше тело и разум — VIP, расслабляющий, для женщин и для пар.',
        'svc_btn': 'Подробнее',
        'all_svc': 'Все массажи',
        'team_label': 'Наша команда',
        'team_title': 'Массажистки',
        'team_sub': 'Опытные специалистки с индивидуальным подходом и глубокими знаниями массажных техник.',
        'all_team': 'Познакомиться с командой',
        'proc_label': 'Ваш путь к расслаблению',
        'proc_title': 'Каждая деталь<br>продумана за вас',
        'reviews_label': 'Отзывы',
        'reviews_title': 'Что говорят гости',
        'reviews_sub': 'Реальные оценки из Google Maps.',
        'reviews_empty': 'Отзывы скоро появятся из Google Maps.',
        'reviews_all': 'Все отзывы в Google',
        'faq_label': 'FAQ',
        'faq_title': 'Ответы на ваши вопросы',
        'faq_all': 'Все вопросы',
        'cta_label': 'Подарите себе',
        'cta_title': 'Ваше тело<br>заслуживает ухода',
        'cta_sub': 'Забронируйте массаж онлайн и погрузитесь в роскошную атмосферу Black Diamond Spa.',
        'cta_btn1': 'Забронировать',
        'cta_btn2': 'Контакты',
        'modal_close': 'Закрыть',
        'modal_svc_title': 'Предлагаемые массажи',
        'modal_reserve': 'Забронировать',
        'steps': [
            ('Выберите массаж', 'Изучите каталог и выберите массаж, который лучше всего отвечает вашим потребностям.'),
            ('Напишите нам', 'Бронирование через WhatsApp или по телефону — напишите нам, и мы подберём удобное время.'),
            ('Подтвердите время', 'Мы сразу подтвердим вашу запись сообщением. Без регистрации и ожидания.'),
            ('Расслабьтесь', 'Приходите за 10 минут. Всё остальное — на нас. Ваше время только для вас.'),
        ],
        'faqs': [
            ('Как подготовиться к массажу?', 'Приходите за 10 минут, чистым и гидратированным. Избегайте еды за час до массажа.'),
            ('Как забронировать массаж?', 'Напишите нам в WhatsApp или позвоните — подберём удобное время и сразу подтвердим запись.'),
            ('Как долго длится массаж?', 'Стандартный массаж длится 60 минут, продлённые варианты — 90 минут. Продолжительность выбираете при записи.'),
            ('Как происходит оплата?', 'Принимаем наличные и карты. Оплата на месте после массажа.'),
            ('Предлагаете парный массаж?', 'Да, парный массаж возможен по запросу. Свяжитесь с нами для бронирования.'),
            ('Что включено в цену?', 'Масляные составы, простыни и доступ к зоне отдыха включены в каждый массаж.'),
        ],
    },
}

FEATURED_SERVICE_SLUGS = ('vip-masaz', 'relaxacni-masaz', 'masaz-pro-zeny', 'masaz-pro-pary')


def get_home_copy(lang):
    code = (lang or 'cs')[:2]
    return HOME_COPY.get(code, HOME_COPY['cs'])
