# Generated by Django 5.2.15 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title_cs', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ru', models.CharField(max_length=120)),
                ('short_cs', models.CharField(blank=True, max_length=200)),
                ('short_en', models.CharField(blank=True, max_length=200)),
                ('short_ru', models.CharField(blank=True, max_length=200)),
                ('description_cs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=60, help_text='Тривалість у хвилинах')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Масаж',
                'verbose_name_plural': 'Масажі',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
