# Generated by Django 4.2.30 on 2026-06-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_cs', models.CharField(max_length=100, verbose_name='Name (CS)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Name (RU)')),
                ('price_czk', models.PositiveIntegerField(default=0, verbose_name='Price (CZK)')),
                ('price_note_cs', models.CharField(blank=True, max_length=100, verbose_name='Price note (CS)')),
                ('price_note_en', models.CharField(blank=True, max_length=100, verbose_name='Price note (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Extra Service',
                'verbose_name_plural': 'Extra Services',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label_cs', models.CharField(max_length=50, verbose_name='Label (CS)')),
                ('label_en', models.CharField(blank=True, max_length=50, verbose_name='Label (EN)')),
                ('label_ru', models.CharField(blank=True, max_length=50, verbose_name='Label (RU)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'HashTag',
                'verbose_name_plural': 'HashTags',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='ISO code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Flag emoji')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='base_duration_min',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Base duration (min)'),
        ),
        migrations.AddField(
            model_name='service',
            name='base_price_czk',
            field=models.PositiveIntegerField(default=0, verbose_name='Base price (CZK)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='services/heroes/', verbose_name='Hero image (local)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_url',
            field=models.URLField(blank=True, verbose_name='Hero image URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon ID (SVG sprite)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='Is extra service'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_cs',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (CS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (CS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveSmallIntegerField(verbose_name='Duration (minutes)')),
                ('price_czk', models.PositiveIntegerField(verbose_name='Price (CZK)')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Highlight (best value)')),
                ('note_cs', models.CharField(blank=True, max_length=100, verbose_name='Note (CS)')),
                ('note_en', models.CharField(blank=True, max_length=100, verbose_name='Note (EN)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['service__order', 'duration_min'],
                'unique_together': {('service', 'duration_min')},
            },
        ),
    ]
