# Generated by Django 4.2.30 on 2026-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_extra_hashtag_language_service_base_duration_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_cs',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (CS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_ru',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_cs',
            field=models.TextField(blank=True, verbose_name='What is it (CS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_en',
            field=models.TextField(blank=True, verbose_name='What is it (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_ru',
            field=models.TextField(blank=True, verbose_name='What is it (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='who_cs',
            field=models.TextField(blank=True, verbose_name='Who is it for (CS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='who_en',
            field=models.TextField(blank=True, verbose_name='Who is it for (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='who_ru',
            field=models.TextField(blank=True, verbose_name='Who is it for (RU)'),
        ),
    ]
