# Generated by Django 5.2.15 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(blank=True, upload_to='masseuses/')),
                ('bio_cs', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_ru', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('specialties', models.ManyToManyField(blank=True, related_name='therapists', to='services.service')),
            ],
            options={
                'verbose_name': 'Масажистка',
                'verbose_name_plural': 'Масажистки',
                'ordering': ['order', 'name'],
            },
        ),
    ]
