# Generated by Django 4.2.30 on 2026-06-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_extra_hashtag_language_service_base_duration_min_and_more'),
        ('media_library', '0001_initial'),
        ('branches', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Масажистка', 'verbose_name_plural': 'Масажистки'},
        ),
        migrations.AddField(
            model_name='therapist',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='branches',
            field=models.ManyToManyField(blank=True, to='branches.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='bust',
            field=models.CharField(blank=True, max_length=10, verbose_name='Bust'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='extras',
            field=models.ManyToManyField(blank=True, to='services.extra', verbose_name='Extra services'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='gallery_cloudinary',
            field=models.ManyToManyField(blank=True, related_name='therapist_gallery', to='media_library.cloudinaryimage', verbose_name='Gallery (library)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='gallery_urls',
            field=models.TextField(blank=True, verbose_name='Gallery image URLs (legacy)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='has_location',
            field=models.BooleanField(default=True, verbose_name='Currently at location'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='has_schedule',
            field=models.BooleanField(default=False, verbose_name='Has schedule entry today'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='services.hashtag', verbose_name='Hashtags / characteristics'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='Show as busy'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New therapist badge'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='languages',
            field=models.ManyToManyField(blank=True, to='services.language', verbose_name='Languages spoken'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='therapists_loves', to='services.service', verbose_name='Loves'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='loves_text_cs',
            field=models.TextField(blank=True, verbose_name='Loves / personality (CS)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='loves_text_en',
            field=models.TextField(blank=True, verbose_name='Loves / personality (EN)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='loves_text_ru',
            field=models.TextField(blank=True, verbose_name='Loves / personality (RU)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='main_cloudinary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_main', to='media_library.cloudinaryimage', verbose_name='Main photo (library)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='main_photo_url',
            field=models.URLField(blank=True, verbose_name='Main photo URL (external)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='therapists_offers', to='services.service', verbose_name='Offers'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sort order'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='use_default',
            field=models.BooleanField(default=False, verbose_name='Use default language content'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
    ]
