# Generated by Django 4.2.30 on 2026-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_therapist_options_therapist_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='faq_cs',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (CS)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (EN)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='faq_ru',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ (RU)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_description_cs',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (CS)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (EN)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (RU)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (CS)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (EN)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (RU)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='tagline_cs',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tagline (CS)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tagline (EN)'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tagline (RU)'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description (legacy)'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (legacy)'),
        ),
    ]
