# Generated by Django 4.2.30 on 2026-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0003_therapist_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='hub_slug',
            field=models.SlugField(blank=True, help_text='Slug масажистки на tantra-prague.com (для синхронізації розкладу)', max_length=80),
        ),
    ]
