# Generated by Django 4.2.30 on 2026-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='Soukenická', max_length=120, verbose_name='Вулиця')),
                ('street_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер будинку')),
                ('postal_code', models.CharField(default='110 00', max_length=20, verbose_name='Поштовий індекс')),
                ('city', models.CharField(default='Praha 1', max_length=80, verbose_name='Місто')),
                ('country_code', models.CharField(default='CZ', max_length=2, verbose_name='Код країни')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
