# Generated by Django 4.2.30 on 2026-06-16 08:58

from decimal import Decimal

from django.db import migrations, models


def enable_multi_currency(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(pk=1).update(
        eur_rate=Decimal('22.09'),
        usd_rate=Decimal('20.00'),
        show_eur=True,
        show_usd=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentpage_etiquetterule_guestreview_legacyredirect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='eur_rate',
            field=models.DecimalField(decimal_places=4, default=22.09, max_digits=8, verbose_name='EUR rate (1 EUR = X CZK)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(default='Od 9 ráno do 4 ráno', max_length=100, verbose_name='Opening hours (Czech — default fallback)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_en',
            field=models.CharField(blank=True, default='From 9 am to 4 am', max_length=100, verbose_name='Opening hours (English)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_ru',
            field=models.CharField(blank=True, default='С 9 утра до 4 утра', max_length=100, verbose_name='Opening hours (Russian)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_usd',
            field=models.BooleanField(default=True, verbose_name='Show prices in USD'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='usd_rate',
            field=models.DecimalField(decimal_places=4, default=20.0, max_digits=8, verbose_name='USD rate (1 USD = X CZK)'),
        ),
        migrations.RunPython(enable_multi_currency, migrations.RunPython.noop),
    ]
