# Generated by Django 5.2.15 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_cs', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('body_cs', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('meta_description_cs', models.CharField(blank=True, max_length=160)),
                ('meta_description_en', models.CharField(blank=True, max_length=160)),
                ('meta_description_ru', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at'],
            },
        ),
    ]
