# Generated by Django 4.2.30 on 2026-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_cs', models.CharField(max_length=300, verbose_name='Question (CS)')),
                ('question_en', models.CharField(blank=True, max_length=300, verbose_name='Question (EN)')),
                ('question_ru', models.CharField(blank=True, max_length=300, verbose_name='Question (RU)')),
                ('answer_cs', models.TextField(verbose_name='Answer (CS)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer (EN)')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Answer (RU)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('include_in_schema', models.BooleanField(default=True, verbose_name='Include in FAQ Schema')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
