# Generated by Django 5.2.15 on 2026-06-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.CharField(choices=[('free', 'Вільно'), ('busy', 'Зайнято'), ('soon', 'Скоро')], default='free', max_length=10)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='therapists.therapist')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоти розкладу',
                'ordering': ['date', 'time_start'],
                'unique_together': {('therapist', 'date', 'time_start')},
            },
        ),
    ]
