# Generated by Django 4.2.30 on 2026-06-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_therapist_options_therapist_age_and_more'),
        ('branches', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('time_from', models.TimeField(verbose_name='From')),
                ('time_to', models.TimeField(verbose_name='To')),
                ('location_address', models.CharField(blank=True, max_length=200, verbose_name='Work address')),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10, verbose_name='Shift')),
                ('note_cs', models.CharField(blank=True, max_length=100, verbose_name='Note (CS)')),
                ('note_en', models.CharField(blank=True, max_length=100, verbose_name='Note (EN)')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='branches.branch', verbose_name='Branch')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='therapists.therapist', verbose_name='Therapist')),
            ],
            options={
                'verbose_name': 'Schedule Entry',
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ['date', 'time_from'],
                'unique_together': {('therapist', 'date', 'time_from')},
            },
        ),
    ]
