# Generated by Django 4.2.30 on 2026-06-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_extra_hashtag_language_service_base_duration_min_and_more'),
        ('branches', '0001_initial'),
        ('therapists', '0002_alter_therapist_options_therapist_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(choices=[('general', 'General / No service'), ('nuru', 'Nuru'), ('lingam', 'Lingam'), ('body', 'Body-to-Body'), ('bdsm', 'BDSM'), ('vip', 'VIP'), ('couple', 'Couples'), ('classic', 'Classic Erotic'), ('pussycat', 'Pussycat'), ('prostate', 'Prostate')], default='general', max_length=30, unique=True, verbose_name='Service key')),
                ('template_cs', models.TextField(help_text='Use {therapist} and {duration} placeholders.', verbose_name='Message template (CS)')),
                ('template_en', models.TextField(blank=True, verbose_name='Message template (EN)')),
                ('template_ru', models.TextField(blank=True, verbose_name='Message template (RU)')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
        migrations.CreateModel(
            name='BookingClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Clicked at')),
                ('channel', models.CharField(db_index=True, max_length=16, verbose_name='Channel')),
                ('placement', models.CharField(db_index=True, max_length=40, verbose_name='Placement')),
                ('page_path', models.CharField(blank=True, max_length=300, verbose_name='Page path')),
                ('lang', models.CharField(blank=True, max_length=5, verbose_name='Language')),
                ('therapist_slug', models.CharField(blank=True, max_length=100, verbose_name='Therapist slug')),
                ('service_slug', models.CharField(blank=True, max_length=100, verbose_name='Service slug')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (min)')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP hash')),
                ('ip_only_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='IP-only hash')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Bot traffic')),
            ],
            options={
                'verbose_name': 'Booking click',
                'verbose_name_plural': 'Booking clicks',
                'ordering': ('-clicked_at',),
                'indexes': [models.Index(fields=['clicked_at', 'placement'], name='booking_boo_clicked_ea19a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Start time')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, verbose_name='Duration (min)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12, verbose_name='Status')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Client name')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Client phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='branches.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Service')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='therapists.therapist', verbose_name='Therapist')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date', '-time_start'],
                'permissions': [('view_confidential_booking', 'Can view confidential booking data')],
            },
        ),
    ]
